packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.9.0
  prettier: ^3.3.3
  typescript: ^5.5.4
  zod: ^3.23.8
  tsx: ^4.7.1
  pkgroll: ^2.4.2
  react: 18.2.0
  react-dom: 18.2.0
  tailwindcss-animate: ^1.0.7
  tailwindcss: ^3.4.10
  tailwind-merge: ^2.5.2
  clsx: ^2.1.1
  class-variance-authority: ^0.7.0
  "@types/node": ^22.5.4
  "@types/react": ~18.2.45
